### ISSUE TITLE
Trouble Starting GameServerApp.exe

### ISSUE THREAD

**Issue by iCraysen** [LeagueSandbox/GameServer#267]
i'm sorry for disturbing you guys with this, but i'm getting this issue.

(28/11/2016 08:46) [CORE_INFO]: Mapped Content [LeagueSandbox-Default][Stats][Zyra]
(28/11/2016 08:46) [CORE_INFO]: Mapped Content [LeagueSandbox-Default][Stats][ZyraGraspingPlant]
(28/11/2016 08:46) [CORE_INFO]: Mapped Content [LeagueSandbox-Default][Stats][ZyraPassive]
(28/11/2016 08:46) [CORE_INFO]: Mapped Content [LeagueSandbox-Default][Stats][ZyraSeed]
(28/11/2016 08:46) [CORE_INFO]: Mapped Content [LeagueSandbox-Default][Stats][ZyraThornPlant]
(28/11/2016 08:46) [CORE_INFO]: Loaded content [LeagueSandbox-Default][Maps][Map1/Map1.json]
(28/11/2016 08:46) [EXCEPTION]: A first chance exception was thrown
(28/11/2016 08:46) [EXCEPTION]: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
(28/11/2016 08:46) [EXCEPTION]: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs
(28/11/2016 08:46) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(28/11/2016 08:46) [UNHANDLEDEXCEPTION]: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
(28/11/2016 08:46) [UNHANDLEDEXCEPTION]: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at ENet.Native.enet_initialize()
   at ENet.Host.Create(Nullable`1 address, Int32 peerLimit, Int32 channelLimit, UInt32 incomingBandwidth, UInt32 outgoingBandwidth) in D:\MEGAsync\LeagueSandbox\GameServer-master\ENetCS\Host.cs:line 83
   at LeagueSandbox.GameServer.Core.Logic.Game.Initialize(Address address, String baseKey) in D:\MEGAsync\LeagueSandbox\GameServer-master\GameServerLib\Logic\Game.cs:line 67
   at LeagueSandbox.GameServer.Server.Start() in D:\MEGAsync\LeagueSandbox\GameServer-master\GameServerLib\Server.cs:line 33
   at LeagueSandbox.GameServer.Program.Run(String configPath, UInt16 serverPort) in D:\MEGAsync\LeagueSandbox\GameServer-master\GameServerLib\Program.cs:line 42
   at LeagueSandbox.GameServer.GameServerLauncher.LaunchServer(String configPath, UInt16 serverPort) in D:\MEGAsync\LeagueSandbox\GameServer-master\GameServerLib\Program.cs:line 15
   at LeagueSandbox.GameServerApp.Program.Main(String[] args) in D:\MEGAsync\LeagueSandbox\GameServer-master\GameServerApp\Program.cs:line 11

**Comment by FurkanS1821** [comment]
This should be fixed when #264 is merged, hope @MythicManiac wakes up and merges that.

**Comment by MythicManiac** [comment]
This should be fixed now. Fetch the latest version and try again.
